---
title: "Projet de Séries Temporelles"
author: "Kim Antunez et Alain Quartier-la-Tente"
date: "31/03/2020"
automaticcontents: true
output:
  bookdown::pdf_document2:
        toc: true
        toc_depth: 3
        number_sections: true
        fig_width: 7
        fig_height: 6
        fig_caption: true
        highlight: default
        keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
  collapse = TRUE,
  fig.path = "img/rmd-",
  fig.align = "center",
  warning = FALSE)
```

# Partie 1 : Les données

## Question 1 : description de la série choisie

Pour ce projet, nous avons choisi de travailler sur la série d'indice de production industrielle (IPI) dans l'industrie automobile (identifiant : 010537940). Il s'agit d'une série au niveau A64 de la nomenclature d'activités française révision 2 (NAF rév. 2), poste CL1.
Cela concerne aussi bien la production des constructeurs de voitures particulières, de véhicules de loisir, de véhicules utilitaires que les équipementiers spécialisés, les carrossiers, les assembleurs ou les prestataires de services d’aménagement de véhicules automobiles. Cette production intègre donc la filière complète, y compris moteurs et or- ganes mécaniques en amont, dès lors qu’ils sont principalement destinés à des véhicules automobiles (à l’exception des parties de moteur).

C'est un indice de Laspeyres chaîné avec des pondérations annuelles en valeur ajouté. Il est de base 2015. L'IPI dans l'industrie automobile est calculé à partir de l'enquête mensuelle de branche. Il est calculé par agrégation de séries "élémentaires" calculées à un niveau plus fin. Ces séries élémentaires sont estimées en volume : la série d'IPI dans l'industrie automobile ne tient donc pas compte des variations de prix.

Les séries de l'IPI sont corrigées des variations saisonnières et des jours ouvrables (CVS-CJO) à partir de la méthode X13-ARIMA. La désaisonnalisation est réalisée de manière indirecte :  elle est effectuée à un niveau fin et les agrégats CVS-CJO sont ensuite calculés directement à partir de ces séries en agrégeant les séries CVS-CJO. Cette désaisonnalisation est réalisée par sous-période pour prendre en compte le fait que la structure économique des séries a beaucoup évolué en 30 ans, et donc qu'il serait peut pertinent d'appliquer un seul modèle de désaisonnalisation sur l'ensemble de la période. Ainsi, les modèles utilisés pour la désaisonnalisation commencent en 2005 et ces modèles sont utilisées pour estimer les séries CVS-CJO à partir de 2012.

Les séries CVS-CJO avant et après 2012 n'étant pas évalués sur les mêmes modèles, et pour éviter des ruptures liées à ce changement de modèle, l'idéal serait d'étudier notre série après janvier 2012. En revanche, cela laisserait une faible profondeur temporelle risquant de fragiliser l'estimation de nos modèles ARIMA. C'est pourquoi nous allons étudier la série d'IPI dans l'industrie automobile entre **janvier 2010 et décembre 2019**^[Les derniers points étant souvent sujets à révisions, nous avons préféré ne pas prendre en compte les points de janvier et février 2020], c'est-à-dire sur **120 observations**.

Nous n'effectuerons pas de correction de point atypique ou de transformation logarithmique.

# Partie 2 : Modèles ARIMA


Pour les tableaux on peut s'inspirer de ce qui est fait dans `rjdmarkdown` : https://aqlt.github.io/rjdmarkdown/articles/rjdmarkdown-pdf.pdf

# Partie 3 : Prévisions

## Question 6, 7 et 8 : construction d'un intervalle de confiance

Refaire cette partie là
https://otexts.com/fpp2/arima-forecasting.html


Pour obtenir ces intervalles de confiance il faut que les résidus de notre modèle ARIMA soient indépendants et suivent une loi normale
The prediction intervals for ARIMA models are based on assumptions that the residuals are uncorrelated and normally distributed. If either of these assumptions does not hold, then the prediction intervals may be incorrect. For this reason, always plot the ACF and histogram of the residuals to check the assumptions before producing prediction intervals.

## Question 9 : question ouverte

Granger
